### ISSUE TITLE
error occurs when Waiting for completion

### ISSUE THREAD

**Issue by kiseoky** [xMistt/DeviceAuthGenerator#3]
Opening new tab => it opens right page on chrome => emit error  before I login or not.

Here's my screenshot

![image](https://user-images.githubusercontent.com/20081840/132087910-0a401187-3bb1-4f32-8b60-b4660ba26c3a.png)

**Comment by ChellyL** [comment]
i got this too, tried many times but still failed

**Comment by ghost** [comment]
its because epic did something to the authentication system(device code)

**Comment by ZaHecc** [comment]
This is the same error I get, pls fix

**Comment by ghost** [comment]
“> its because epic did something to the authentication system(device code)”

**Comment by lz0709** [comment]
> its because epic did something to the authentication system(device code)

so do you know how to avoid it?

**Comment by stickerx** [comment]
how to fix this

**Comment by Cairl** [comment]
same like you, how do i do?

**Comment by stickerx** [comment]
I still have this problem

**Comment by jackblk** [comment]
I fixed & tested this issue on my fork.

While waiting for @xMistt to merge, I created my own release here so you can use the executable on Windows: https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1

PR created: https://github.com/xMistt/DeviceAuthGenerator/pull/8

After checking on discord, I think the author is not in the condition to maintain. If @xMistt does not merge or maintain in a few months, I will try to maintain on my fork.

**Comment by Cairl** [comment]
> I fixed & tested this issue on my fork.
> 
> While waiting for @xMistt to merge, I created my own release here so you can use the executable on Windows: https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1
> 
> PR created: #8
> 
> After checking on discord, I think the author is not in the condition to maintain. If @xMistt does not merge or maintain in a few months, I will try to maintain on my fork.

thank you! it is worth!

**Comment by Monst3rX** [comment]
Still doesnt work for, with the latest version, anything happenned?

**Comment by jackblk** [comment]
> Still doesnt work for, with the latest version, anything happenned?

Have you tried my fork?: https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1

**Comment by Monst3rX** [comment]
> > Still doesnt work for, with the latest version, anything happenned?
> 
> Have you tried my fork?: https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1
Yes and it have the same error I can record if you need or send a screenshot?

**Comment by jackblk** [comment]
@kolgkhfp I can't reproduce on my end with my fork. Can you try on another PC/network?

**Comment by Shaggygoblin** [comment]
> I fixed & tested this issue on my fork.
> 
> While waiting for @xMistt to merge, I created my own release here so you can use the executable on Windows: https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1
> 
> PR created: #8
> 
> After checking on discord, I think the author is not in the condition to maintain. If @xMistt does not merge or maintain in a few months, I will try to maintain on my fork.

@jackblk 's fix is confirmed working for me.
https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1

**Comment by BaesFr** [comment]
@jackblk it's perfect !
Thanks a lot 

I just download the new device generator, run it, to have a new device_auths.json, put it in "data" folder and run as usual.

Works like a charm

Did I say thanks a lot ?

**Comment by xMistt** [comment]
Do you still experience this? It's working fine for me.
